In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import re
%matplotlib inline

In [109]:
mum_df = pd.read_csv('../datasets/mumbai.csv')

In [110]:
del_df = pd.read_csv('../datasets/delhi.csv')

In [130]:
met_df = pd.read_csv('../datasets/cleaned_dataset.csv', index_col=0)

In [131]:
met_df['rest_type']

0        Casual Dining
1           Sweet Shop
2          Quick Bites
3               Bakery
4        Casual Dining
             ...      
15428     North Indian
15429      Quick Bites
15430           Bakery
15431     North Indian
15433      Quick Bites
Name: rest_type, Length: 15433, dtype: object

In [132]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
le = LabelEncoder()
ohe = OneHotEncoder(sparse=False)

In [133]:
val = le.fit_transform(met_df['rest_type']).reshape(-1,1)

In [134]:
val

array([[17],
       [89],
       [75],
       ...,
       [ 6],
       [68],
       [75]])

In [135]:
res = met_df['rest_type'].values

In [136]:
res

array(['Casual Dining', 'Sweet Shop', 'Quick Bites', ..., 'Bakery',
       'North Indian', 'Quick Bites'], dtype=object)

In [137]:
res = ohe.fit_transform(val)

In [138]:
res = pd.DataFrame(res)

In [139]:
res

0    1    2    3    4    5    6    7    8    9   ...   84   85   86  \
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3      0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
15428  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
15429  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
15430  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
15431  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
15432  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        87   88   89   90   91   92   93  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      0.0  0.0  1.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  ...  ...  ...  
15428  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
15429  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
15430  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
15431  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
15432  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[15433 rows x 94 columns]

In [143]:
new = pd.concat([met_df,res], axis=1)

In [141]:
#eq = le.transform(['Casual Dining']).reshape(-1,1)

In [86]:
#res = ohe.transform(eq)

In [87]:
#res

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [148]:
new.dropna(inplace=True)

In [151]:
new.drop('rest_type', axis=1, inplace=True)

In [155]:
new.head(1)

book_table  can_order_via_zomato  cost_for_two  delivery_reviews  \
0         0.0                   1.0         600.0             875.0   

   dining_reviews  discount  has_menu_available  review_rating  dining_rating  \
0          3524.0       0.0                 1.0            3.4            4.1   

   delivery_rating  ...   84   85   86   87   88   89   90   91   92   93  
0              3.9  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1 rows x 104 columns]

In [159]:
X = new.drop('cost_for_two', axis=1)
y = new['cost_for_two']

In [178]:
X_train = X[:round(0.7*len(X))]
X_valid = X[round(0.7*len(X))+1 : -round(0.15*len(X))]
X_test = X[-round(0.15*len(X)):]
#y
Y_train = y[:round(0.7*len(y))]
Y_valid = y[round(0.7*len(y))+1 : -round(0.15*len(y))]
Y_test = y[-round(0.15*len(y)):]

In [176]:
X_test

book_table  can_order_via_zomato  delivery_reviews  dining_reviews  \
13117         0.0                   0.0        622.081881       70.000000   
13118         0.0                   0.0        622.081881       61.000000   
13119         0.0                   1.0        622.081881        6.000000   
13120         0.0                   0.0        622.081881        5.000000   
13121         0.0                   0.0        622.081881       10.000000   
...           ...                   ...               ...             ...   
15427         0.0                   0.0        348.000000      147.012891   
15428         0.0                   1.0       2231.000000      147.012891   
15429         0.0                   1.0       1736.000000      230.000000   
15430         0.0                   1.0        701.000000      147.012891   
15431         0.0                   0.0        613.000000      147.012891   

       discount  has_menu_available  review_rating  dining_rating  \
13117       0.0                 1.0            4.8            3.1   
13118       0.0                 1.0            3.0            3.6   
13119       0.0                 1.0            5.0            2.8   
13120       0.0                 1.0            4.2            3.0   
13121       0.0                 1.0            5.0            3.3   
...         ...                 ...            ...            ...   
15427       0.0                 1.0            5.0            3.6   
15428      10.0                 1.0            5.0            3.2   
15429       0.0                 1.0            5.0            4.2   
15430      20.0                 1.0            4.6            3.7   
15431       0.0                 1.0            5.0            3.3   

       delivery_rating    0  ...   84   85   86   87   88   89   90   91   92  \
13117         1.365971  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
13118         1.365971  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
13119         1.365971  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
13120         1.365971  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
13121         1.365971  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
15427         1.365971  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15428         1.365971  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15429         3.700000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15430         1.365971  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
15431         1.365971  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

        93  
13117  0.0  
13118  0.0  
13119  0.0  
13120  0.0  
13121  0.0  
...    ...  
15427  0.0  
15428  0.0  
15429  0.0  
15430  0.0  
15431  0.0  

[2315 rows x 103 columns]

In [191]:
node = [[1,1,340,240,10,1, 'Casual Dining', 3.8, 4.0, 4.3]]

In [192]:
node = pd.DataFrame(node)

In [193]:
node.columns = met_df.drop('cost_for_two',axis=1).columns

In [194]:
node

book_table  can_order_via_zomato  delivery_reviews  dining_reviews  \
0           1                     1               340             240   

   discount  has_menu_available      rest_type  review_rating  dining_rating  \
0        10                   1  Casual Dining            3.8            4.0   

   delivery_rating  
0              4.3

In [30]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

met_df = pd.read_csv('../datasets/cleaned_dataset.csv', index_col=0)

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
le = LabelEncoder()
ohe = OneHotEncoder(sparse=False)

val = le.fit_transform(met_df['rest_type']).reshape(-1,1)

res = met_df['rest_type'].values
res = ohe.fit_transform(val)
res = pd.DataFrame(res)
new = pd.concat([met_df,res], axis=1)
new.dropna(inplace=True)
new.drop('rest_type', axis=1, inplace=True)
X = new.drop('cost_for_two', axis=1)
y = new['cost_for_two']

X_train = X[:round(0.7*len(X))]
X_valid = X[round(0.7*len(X))+1 : -round(0.15*len(X))]
X_test = X[-round(0.15*len(X)):]
#y
y_train = y[:round(0.7*len(y))]
y_valid = y[round(0.7*len(y))+1 : -round(0.15*len(y))]
y_test = y[-round(0.15*len(y)):]

from sklearn.ensemble import RandomForestRegressor
#rf_100 = RandomForestRegressor(n_estimators=100, criterion='mae')
#rf_100.fit(X_train, y_train)

#pickle.dump(rf_100, open('model.pkl','wb'))

#model = pickle.load(open('model.pkl','rb'))
node = [[1,1,340,240,10,1, 'Casual Dining', 3.8, 4.0, 4.3]]
node = pd.DataFrame(node)
node.columns = met_df.drop('cost_for_two',axis=1).columns
val = le.transform(node['rest_type']).reshape(-1,1)
res = node['rest_type'].values
res = ohe.transform(val)
res = pd.DataFrame(res)
new = pd.concat([node,res], axis=1)
new.dropna(inplace=True)
new.drop('rest_type', axis=1, inplace=True)
#print(model.predict(node))

In [22]:
met_df.head(1)

book_table  can_order_via_zomato  cost_for_two  delivery_reviews  \
0           0                     1         600.0             875.0   

   dining_reviews  discount  has_menu_available      rest_type  review_rating  \
0          3524.0       0.0                   1  Casual Dining            3.4   

   dining_rating  delivery_rating  
0            4.1              3.9

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

met_df = pd.read_csv('../datasets/cleaned_dataset.csv', index_col=0)

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
le = LabelEncoder()
ohe = OneHotEncoder(sparse=False)

val = le.fit_transform(met_df['rest_type']).reshape(-1,1)

res = met_df['rest_type'].values
res = ohe.fit_transform(val)
res = pd.DataFrame(res)
new = pd.concat([met_df,res], axis=1)
new.dropna(inplace=True)
new.drop('rest_type', axis=1, inplace=True)
X = new.drop('cost_for_two', axis=1)
y = new['cost_for_two']

X_train = X[:round(0.7*len(X))]
X_valid = X[round(0.7*len(X))+1 : -round(0.15*len(X))]
X_test = X[-round(0.15*len(X)):]
#y
y_train = y[:round(0.7*len(y))]
y_valid = y[round(0.7*len(y))+1 : -round(0.15*len(y))]
y_test = y[-round(0.15*len(y)):]

from sklearn.ensemble import RandomForestRegressor
print("modelling.....")
rf_100 = RandomForestRegressor(n_estimators=50, criterion='mae')
rf_100.fit(X_train, y_train)
print("modelling done.....")

# pickle.dump(rf_100, open('model.pkl','wb'))
# pickle.dump(le, open('label.pkl','wb'))
# pickle.dump(ohe, open('hot.pkl','wb'))

# model = pickle.load(open('model.pkl','rb'))
# le = pickle.load(open('label.pkl','rb'))
# ohe = pickle.load(open('hot.pkl','rb'))

node = [[1,1,340,240,10,1, 'Casual Dining', 3.8, 4.0, 4.3]]
node = pd.DataFrame(node)
node.columns = met_df.drop('cost_for_two',axis=1).columns
val = le.transform(node['rest_type']).reshape(-1,1)
res = node['rest_type'].values
res = ohe.transform(val)
res = pd.DataFrame(res)
new = pd.concat([node,res], axis=1)
new.dropna(inplace=True)
new.drop('rest_type', axis=1, inplace=True)
print(rf_100.predict(new))















#https://towardsdatascience.com/how-to-easily-deploy-machine-learning-models-using-flask-b95af8fe34d4


#https://towardsdatascience.com/create-an-api-to-deploy-machine-learning-models-using-flask-and-heroku-67a011800c50

modelling.....
modelling done.....


NameError: name 'model' is not defined

In [19]:
met_df['cost_for_two'].unique()

array([  600.,   300.,   900.,   700.,   800.,   450.,  1000.,   400.,
         100.,   500.,  1500.,   650.,   250.,   950.,   550.,   200.,
         150.,  1100.,   350.,  1800.,  2000.,  2200.,  1200.,  1300.,
         750.,   850.,  1900.,  1600.,  2800.,  2500.,  2100.,  1700.,
        1400.,  4500.,  7900.,  2600.,  2400.,  2300.,  5000.,  6000.,
        3500.,  4000.,  1550.,  3000.,  1050., 10000.,  4200.,  1450.,
        2700.,   360.,    50.,   260.,     0.,  5500.,  1650.,   340.,
        1150.,  6500.,  4050.,   120.,  3300.,  5100.,  3200.,  3700.,
        3800.,  8000.,  3400.,  6600.,  7000.,  3600.])

In [20]:
met_df['rest_type'].unique()

array(['Casual Dining', 'Sweet Shop', 'Quick Bites', 'Bakery',
       'Dessert Parlor', 'Bar', 'Beverage Shop', 'South Indian',
       'Chinese', 'Fast Food', 'Rolls', 'Café', 'Pizza', 'Fine Dining',
       'Biryani', 'Asian', 'Momos', 'Pub', 'Healthy Food', 'North Indian',
       'Club', 'Kiosk', 'Bengali', 'Dhaba', 'Korean', 'Lounge',
       'Sandwich', 'Tea', 'Lebanese', 'Food Truck', 'American', 'Mexican',
       'Street Food', 'Raw Meats', 'Food Court', 'Kebab', 'Mughlai',
       'Burger', 'Continental', 'Arabian', 'Irani Cafe', 'Bihari',
       'Ice Cream', 'Roast Chicken', 'Maharashtrian', 'Confectionery',
       'Japanese', 'Italian', 'Desserts', 'Mithai', 'Seafood',
       'Beverages', 'Paan Shop', 'Mangalorean', 'Malwani', 'Kerala',
       'Salad', 'Konkan', 'Tibetan', 'Thai', 'Juices', 'Wraps', 'Sindhi',
       'Sushi', 'Cuisine Varies', 'Shack', 'Bhojanalya', 'Awadhi', 'Paan',
       'Indonesian', 'Hyderabadi', 'BBQ', 'Gujarati', 'Mediterranean',
       'Parsi', 'Rajasthani

In [21]:
node = [[1,1,100,240,20,0, 'Bakery', 2.8, 2, 0]]
node = pd.DataFrame(node)
node.columns = met_df.drop('cost_for_two',axis=1).columns
val = le.transform(node['rest_type']).reshape(-1,1)
res = node['rest_type'].values
res = ohe.transform(val)
res = pd.DataFrame(res)
new = pd.concat([node,res], axis=1)
new.dropna(inplace=True)
new.drop('rest_type', axis=1, inplace=True)
print(rf_100.predict(new))


[649.]
